version: "3"
services:
  drive:
    image: rclone-drive:test
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN    
    devices:
      - "/dev/fuse"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - type: bind
        source: ${HOME}/Dev/docker-rclone-drive/data
        target: /mount
        bind:
          propagation: shared
    restart: unless-stopped
    mem_limit: 4g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - GOOGLE_CLIENTID=${GOOGLE_CLIENTID}
      - GOOGLE_CLIENTSECRET=${GOOGLE_CLIENTSECRET}
      - DRIVE_ROOTFOLDER=${DRIVE_ROOTFOLDER}
      - DRIVE_PROJECT_ID=${DRIVE_PROJECT_ID}
      - DRIVE_PRIVATE_KEY_ID=${DRIVE_PRIVATE_KEY_ID}
      - DRIVE_PRIVATE_KEY=${DRIVE_PRIVATE_KEY}
      - DRIVE_CLIENT_EMAIL=${DRIVE_CLIENT_EMAIL}
      - DRIVE_CLIENT_ID=${DRIVE_CLIENT_ID}
      - DRIVE_CERTIFICATE_URL=${DRIVE_CERTIFICATE_URL}
      - GCRYPT_PASSWORD=${GCRYPT_PASSWORD}
      - GCRYPT_PASSWORD2=${GCRYPT_PASSWORD2}
      - DRIVE_TARGETFOLDER=${DRIVE_TARGETFOLDER}
      - DRIVE_MOUNTFOLDER=${DRIVE_MOUNTFOLDER}