---
version: "3"
services:
  drive:
    image: rclone-drive:test
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - type: bind
        source: ./data
        target: /mount${DRIVE_MOUNTFOLDER}
        bind:
          propagation: shared
    restart: unless-stopped
    mem_limit: 4g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - USER_EMAIL=${USER_EMAIL}
      - DRIVE_MOUNTFOLDER=${DRIVE_MOUNTFOLDER}
      - RCLONE_BUFFER_SIZE=
      - RCLONE_ZFS_CACHE_MODE=full
      - RCLONE_ZFS_READ_AHEAD=
      - RCLONE_TEAMDRIVE=false
      - RCLONE_CACHE=false
      - DRIVE_TARGETFOLDER=
      - GOOGLE_CLIENTID=${GOOGLE_CLIENTID}
      - GOOGLE_CLIENTSECRET=${GOOGLE_CLIENTID}
      - DRIVE_ROOTFOLDER=${DRIVE_ROOTFOLDER}
      - GCRYPT_PASSWORD=${GCRYPT_PASSWORD}
      - GCRYPT_PASSWORD2=${GCRYPT_PASSWORD2}
      - DRIVE_PROJECT_ID=${DRIVE_PROJECT_ID}
      - DRIVE_PRIVATE_KEY_ID=${DRIVE_PRIVATE_KEY_ID}
      - DRIVE_PRIVATE_KEY=${DRIVE_PRIVATE_KEY}
      - DRIVE_CLIENT_EMAIL=${DRIVE_CLIENT_EMAIL}
      - DRIVE_CLIENT_ID=${DRIVE_CLIENT_ID}
      - DRIVE_CERTIFICATE_URL=${DRIVE_CERTIFICATE_URL}
